/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_e2dev_jni_NativeSingleton */

#ifndef _Included_com_e2dev_jni_NativeSingleton
#define _Included_com_e2dev_jni_NativeSingleton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_e2dev_jni_NativeSingleton
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_e2dev_jni_NativeSingleton_nativePrint
  (JNIEnv *, jobject);

/*
 * Class:     com_e2dev_jni_NativeSingleton
 * Method:    getTestNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_e2dev_jni_NativeSingleton_getTestNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
